dotfiles:
  - name: ${HOME}/.zshrc
  - name: ${HOME}/.bash_profile
  - name: ${HOME}/.bashrc
  - name: ${HOME}/.vimrc
  - name: ${HOME}/.gitconfig
  - name: ${HOME}/.gitignore_global
  - name: ${HOME}/.tmux.conf
  - name: ${HOME}/.ssh/config
  - name: ${HOME}/.config/nvim/init.vim
  - name: ${HOME}/.hyper.js
  - name: ${HOME}/.npmrc
  - name: ${HOME}/.yarnrc
  - name: ${HOME}/.editorconfig
  - name: ${HOME}/.aliases
  - name: ${HOME}/.functions
  - name: ${HOME}/.inputrc
  - name: ${HOME}/.hushlogin
  - name: ${HOME}/.curlrc
  - name: ${HOME}/.wgetrc
  - name: ${HOME}/.gemrc
  - name: ${HOME}/.config/alacritty/alacritty.yml
  - name: ${HOME}/.config/karabiner/karabiner.json
  - name: ${HOME}/.config/iterm2/com.googlecode.iterm2.plist
  - name: ${HOME}/.aws/config
  - name: ${HOME}/.aws/credentials
  - name: ${HOME}/.docker/config.json
